### ISSUE TITLE
AdGuardHome控制台的登陆账号密码是什么

### ISSUE THREAD

**Issue by 81508819** [AUK9527/Are-u-ok#66]
AdGuardHome控制台的登陆账号密码是什么

**Comment by GeorgeCiao** [comment]
同问：密码是什么？

**Comment by ac431** [comment]
我也想问，不是admin

**Comment by cuihairu** [comment]
我的用户名是root,密码是admin

可以编辑 `/etc/AdGuardHome.yaml` 修改

```yaml
users:
  - name: root
    password: $2y$10$ML7v5WXsM1xN12YpR15f4uSGGAzk.QXhwu99lczQ8NgrPcTYRY9Ei
```
